// EdgeCraftRAG/ui/vue/src/layout/Main.vue
<template>
  <a-layout class="layout-container">
    <a-layout-header class="layout-header">
      <Header />
    </a-layout-header>
    <a-layout-content class="layout-main">
      <router-view class="layout-view" />
    </a-layout-content>
  </a-layout>
</template>
<script lang="ts" setup name="Main">
import Header from './Header.vue';

</script>
<style lang="less"></style>

// DocSummarization/frontend/src/components/layout/Layout.jsx
import { Outlet } from 'react-router-dom';
import Header from './Header';
import Footer from './Footer';

export const Layout = () => {
  return (
    <div className="flex flex-col min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      <Header />
      <main className="flex-1 container mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <Outlet />
      </main>
      <Footer />
    </div>
  );
};

export default Layout;
