// RAGChatbot/ui/src/components/Header.jsx
import { MessageSquare, FileText } from 'lucide-react'

export default function Header() {
  return (
    <header className="bg-white border-b border-gray-200 shadow-sm">
      <div className="container mx-auto px-4 py-4 max-w-6xl">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="bg-gradient-to-br from-blue-500 to-purple-600 p-2 rounded-lg">
              <MessageSquare className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-2xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                RAG Chatbot
              </h1>
              <p className="text-sm text-gray-500">Ask questions about your documents</p>
            </div>
          </div>
          
          <div className="flex items-center space-x-2 text-sm text-gray-500">
            <FileText className="w-4 h-4" />
          </div>
        </div>
      </div>
    </header>
  )
}

// SearchQnA/ui/src/lib/shared/components/header/header.svelte
<script>

  import IntelLogo from "$lib/assets/header/intelLogo.svelte";

</script>
<header
  class="sticky top-0 z-40 flex-none w-full mx-auto bg-[#0054ae] border-b border-gray-200 dark:border-gray-600 dark:bg-gray-800"
>
  <nav
    class="bg-[#0054ae] dark:bg-gray-800 text-gray-500 dark:text-gray-400 border-gray-200 dark:border-gray-700 divide-gray-200 dark:divide-gray-700 px-2 sm:px-4 w-full py-1.5"
  >
    <div class="mx-auto flex flex-wrap justify-between items-center w-full">
        <IntelLogo />
      <span
        class="self-center whitespace-nowrap text-2xl font-semibold text-white ml-4"
        data-svelte-h="svelte-1hbktnk">Web Search Chatbot</span
      >
    </div>
  </nav>
</header>
